services:
    thuata_framework.stackgeneratorservice:
        class: Thuata\FrameworkBundle\Service\EntityStackGeneratorService
        calls:
            - ['setGenerator', [ "@thuata_intercession.generator" ]]
    thuata_framework.servicefactory:
        class: Thuata\FrameworkBundle\Service\ServiceFactory
        calls:
            - ['setContainer', [ "@service_container" ]]
    thuata_framework.managerfactory:
        class: Thuata\FrameworkBundle\Manager\ManagerFactory
        calls:
            - ['setContainer', [ "@service_container" ]]
    thuata_framework.repositoryfactory:
        class: Thuata\FrameworkBundle\Repository\RepositoryFactory
        calls:
            - ['setContainer', [ "@service_container" ]]
    thuata_framework.registryfactory:
        class: Thuata\FrameworkBundle\Repository\Registry\RegistryFactory
        calls:
            - ['setContainer', [ "@service_container" ]]